# Generated by Django 3.1.4 on 2021-02-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('barrio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=30)),
                ('correo', models.EmailField(max_length=105)),
                ('telefono', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('calle1', models.CharField(max_length=100)),
                ('calle2', models.CharField(max_length=100)),
                ('referencia1', models.CharField(max_length=150)),
                ('referencia2', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.barrio')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('chofer_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.persona')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('agente_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.persona')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.registro')),
            ],
        ),
    ]
