# Generated by Django 3.1.4 on 2021-02-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='registro',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
