# Generated by Django 3.1.4 on 2021-02-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20210224_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='funcion',
            field=models.CharField(choices=[('chofer', 'Chofer'), ('call center', 'Call Center')], default='femenino', max_length=30),
        ),
        migrations.DeleteModel(
            name='Chofer',
        ),
    ]
