# Generated by Django 3.1.4 on 2021-02-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20210225_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
