# Generated by Django 3.1.4 on 2021-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_auto_20210225_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='funcion',
            field=models.CharField(choices=[('chofer', 'Chofer'), ('callCenter', 'Call Center')], default='femenino', max_length=30),
        ),
    ]
