# Generated by Django 3.1.4 on 2021-02-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_auto_20210225_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='funcion',
            field=models.CharField(choices=[('Chofer', 'Chofer'), ('Call Center', 'Call Center')], default='femenino', max_length=30),
        ),
    ]
