# Generated by Django 3.1.4 on 2021-02-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0008_auto_20210225_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
